# Construct Prompts

import asyncio

from dotenv import load_dotenv
from langchain_anthropic import ChatAnthropic



load_dotenv()

model = ChatAnthropic(model='claude-sonnet-4-6', max_tokens_to_sample=64)

async def stream_response_events():
  event_limit = 0
  prompt = "Describe the utilitarianism"
  
  async for event_chunk in model.astream_events(prompt, version='v2'):
    event_limit+=1
    if event_limit >=5:
      print("...Event Streaming Done...")
    print(event_chunk)

asyncio.run(stream_response_events())

"""
{'event': 'on_chat_model_start', 'data': {'input': 'Describe the utilitarianism'}, 'name': 'ChatAnthropic', 'tags': [], 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content='', additional_kwargs={}, response_metadata={'model_name': 'claude-sonnet-4-6', 'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content='#', additional_kwargs={}, response_metadata={'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content=' Utilitarianism', additional_kwargs={}, response_metadata={'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
...Event Streaming Done...
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content='\n\n##', additional_kwargs={}, response_metadata={'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
...Event Streaming Done...
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content=' Core', additional_kwargs={}, response_metadata={'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
...Event Streaming Done...
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content=' Principle', additional_kwargs={}, response_metadata={'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
...Event Streaming Done...
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content='\n\nUtilitarianism is an', additional_kwargs={}, response_metadata={'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
...Event Streaming Done...
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content=' ethical theory holding', additional_kwargs={}, response_metadata={'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
...Event Streaming Done...
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content=' that the', additional_kwargs={}, response_metadata={'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
...Event Streaming Done...
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content=' **', additional_kwargs={}, response_metadata={'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
...Event Streaming Done...
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content='mor', additional_kwargs={}, response_metadata={'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
...Event Streaming Done...
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content='ally', additional_kwargs={}, response_metadata={'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
...Event Streaming Done...
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content=' right action is the one that produces', additional_kwargs={}, response_metadata={'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
...Event Streaming Done...
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content=' the greatest good', additional_kwargs={}, response_metadata={'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
...Event Streaming Done...
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content=' for the greatest number of people**.', additional_kwargs={}, response_metadata={'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
...Event Streaming Done...
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content=' It judges', additional_kwargs={}, response_metadata={'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
...Event Streaming Done...
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content=' actions solely', additional_kwargs={}, response_metadata={'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
...Event Streaming Done...
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content=' by their **', additional_kwargs={}, response_metadata={'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
...Event Streaming Done...
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content='consequences**.', additional_kwargs={}, response_metadata={'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
...Event Streaming Done...
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content='\n\n---', additional_kwargs={}, response_metadata={'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
...Event Streaming Done...
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content='\n\n## Key Founders', additional_kwargs={}, response_metadata={'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
...Event Streaming Done...
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content='\n\n-', additional_kwargs={}, response_metadata={'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
...Event Streaming Done...
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content=' **', additional_kwargs={}, response_metadata={'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[])}, 'parent_ids': []}
...Event Streaming Done...
{'event': 'on_chat_model_stream', 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'data': {'chunk': AIMessageChunk(content='', additional_kwargs={}, response_metadata={'stop_reason': 'max_tokens', 'stop_sequence': None, 'model_provider': 'anthropic'}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 14, 'output_tokens': 64, 'total_tokens': 78, 'input_token_details': {'cache_creation': 0, 'cache_read': 0}}, tool_call_chunks=[], chunk_position='last')}, 'parent_ids': []}      
...Event Streaming Done...
{'event': 'on_chat_model_end', 'data': {'output': AIMessageChunk(content='# Utilitarianism\n\n## Core Principle\n\nUtilitarianism is an ethical theory holding that the **morally right action is the one that produces the greatest good for the greatest number of people**. It judges actions solely by their **consequences**.\n\n---\n\n## Key Founders\n\n- **', additional_kwargs={}, response_metadata={'model_name': 'claude-sonnet-4-6', 'model_provider': 'anthropic', 'stop_reason': 'max_tokens', 'stop_sequence': None}, id='lc_run--019ce01d-5373-7422-ac0e-bf3749a9f1b4', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 14, 'output_tokens': 64, 'total_tokens': 78, 'input_token_details': {'cache_creation': 0, 'cache_read': 0}}, tool_call_chunks=[], chunk_position='last')}, 'run_id': '019ce01d-5373-7422-ac0e-bf3749a9f1b4', 'name': 'ChatAnthropic', 'tags': [], 'metadata': {'ls_provider': 'anthropic', 'ls_model_name': 'claude-sonnet-4-6', 'ls_model_type': 'chat', 'ls_temperature': None, 'ls_max_tokens': 64}, 'parent_ids': []}
"""
